"""add congestion pipeline tables

Revision ID: f3802d323f36
Revises: k3f6a0b14c2d
Create Date: 2026-02-28 11:22:10.207360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3802d323f36'
down_revision: Union[str, Sequence[str], None] = 'k3f6a0b14c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('efiling_url', sa.String(length=500), nullable=True),
    sa.Column('efiling_type', sa.String(length=50), nullable=True),
    sa.Column('api_available', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('utilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_code', sa.String(length=50), nullable=False),
    sa.Column('utility_name', sa.String(length=200), nullable=False),
    sa.Column('parent_company', sa.String(length=200), nullable=True),
    sa.Column('iso_id', sa.Integer(), nullable=True),
    sa.Column('states', sa.JSON(), nullable=True),
    sa.Column('data_source_type', sa.String(length=50), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('service_url', sa.String(length=500), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('eia_id', sa.Integer(), nullable=True),
    sa.Column('utility_type', sa.String(length=30), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('regulator_id', sa.Integer(), nullable=True),
    sa.Column('customers_total', sa.Integer(), nullable=True),
    sa.Column('sales_mwh', sa.Float(), nullable=True),
    sa.Column('service_territory_counties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['iso_id'], ['isos.id'], ),
    sa.ForeignKeyConstraint(['regulator_id'], ['regulators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eia_id'),
    sa.UniqueConstraint('utility_code')
    )
    op.create_index('ix_utilities_eia_id', 'utilities', ['eia_id'], unique=False)
    op.create_index('ix_utilities_iso_id', 'utilities', ['iso_id'], unique=False)
    op.create_index('ix_utilities_regulator_id', 'utilities', ['regulator_id'], unique=False)
    op.create_index('ix_utilities_state', 'utilities', ['state'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('regulator_id', sa.Integer(), nullable=True),
    sa.Column('docket_number', sa.String(length=100), nullable=True),
    sa.Column('filing_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_document_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulator_id'], ['regulators.id'], ),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filings_docket', 'filings', ['docket_number'], unique=False)
    op.create_index('ix_filings_regulator', 'filings', ['regulator_id'], unique=False)
    op.create_index('ix_filings_type', 'filings', ['filing_type'], unique=False)
    op.create_index('ix_filings_utility', 'filings', ['utility_id'], unique=False)
    op.create_table('hc_ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_written', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosting_capacity_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('total_feeders', sa.Integer(), nullable=False),
    sa.Column('total_hosting_capacity_mw', sa.Float(), nullable=False),
    sa.Column('total_installed_dg_mw', sa.Float(), nullable=False),
    sa.Column('total_remaining_capacity_mw', sa.Float(), nullable=False),
    sa.Column('avg_utilization_pct', sa.Float(), nullable=True),
    sa.Column('constrained_feeders_count', sa.Integer(), nullable=False),
    sa.Column('constraint_breakdown', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utility_id')
    )
    op.create_table('interconnection_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=True),
    sa.Column('iso_id', sa.Integer(), nullable=True),
    sa.Column('queue_id', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('point_of_interconnection', sa.String(length=300), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('generation_type', sa.String(length=50), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('capacity_mw_storage', sa.Float(), nullable=True),
    sa.Column('queue_status', sa.String(length=50), nullable=True),
    sa.Column('date_entered', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('date_withdrawn', sa.Date(), nullable=True),
    sa.Column('proposed_online_date', sa.Date(), nullable=True),
    sa.Column('study_phase', sa.String(length=50), nullable=True),
    sa.Column('voltage_kv', sa.Float(), nullable=True),
    sa.Column('substation_name', sa.String(length=300), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['iso_id'], ['isos.id'], ),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interconnection_queue_geom', 'interconnection_queue', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_iq_geom', 'interconnection_queue', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_iq_state', 'interconnection_queue', ['state'], unique=False)
    op.create_index('ix_iq_status', 'interconnection_queue', ['queue_status'], unique=False)
    op.create_index('ix_iq_type', 'interconnection_queue', ['generation_type'], unique=False)
    op.create_index('ix_iq_utility', 'interconnection_queue', ['utility_id'], unique=False)
    op.create_table('filing_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('raw_path', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filing_docs_filing', 'filing_documents', ['filing_id'], unique=False)
    op.create_table('grid_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('location_name', sa.String(length=300), nullable=True),
    sa.Column('location_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('current_capacity_mw', sa.Float(), nullable=True),
    sa.Column('forecasted_load_mw', sa.Float(), nullable=True),
    sa.Column('constraint_year', sa.Integer(), nullable=True),
    sa.Column('headroom_mw', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('raw_source_reference', sa.String(length=300), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grid_constraints_location_geom', 'grid_constraints', ['location_geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_gc_filing', 'grid_constraints', ['filing_id'], unique=False)
    op.create_index('ix_gc_geom', 'grid_constraints', ['location_geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_gc_type', 'grid_constraints', ['constraint_type'], unique=False)
    op.create_index('ix_gc_utility', 'grid_constraints', ['utility_id'], unique=False)
    op.create_table('load_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('forecast_year', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=200), nullable=True),
    sa.Column('area_type', sa.String(length=50), nullable=True),
    sa.Column('peak_demand_mw', sa.Float(), nullable=True),
    sa.Column('energy_gwh', sa.Float(), nullable=True),
    sa.Column('growth_rate_pct', sa.Float(), nullable=True),
    sa.Column('scenario', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lf_filing', 'load_forecasts', ['filing_id'], unique=False)
    op.create_index('ix_lf_utility', 'load_forecasts', ['utility_id'], unique=False)
    op.create_index('ix_lf_year', 'load_forecasts', ['forecast_year'], unique=False)
    op.create_table('resource_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('need_type', sa.String(length=50), nullable=False),
    sa.Column('need_mw', sa.Float(), nullable=True),
    sa.Column('need_year', sa.Integer(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('eligible_resource_types', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rn_filing', 'resource_needs', ['filing_id'], unique=False)
    op.create_index('ix_rn_utility', 'resource_needs', ['utility_id'], unique=False)
    op.create_index('ix_rn_year', 'resource_needs', ['need_year'], unique=False)
    op.create_table('hosting_capacity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('feeder_id_external', sa.String(length=200), nullable=False),
    sa.Column('feeder_name', sa.String(length=300), nullable=True),
    sa.Column('substation_name', sa.String(length=300), nullable=True),
    sa.Column('substation_id', sa.Integer(), nullable=True),
    sa.Column('feeder_id', sa.Integer(), nullable=True),
    sa.Column('hosting_capacity_mw', sa.Float(), nullable=True),
    sa.Column('hosting_capacity_min_mw', sa.Float(), nullable=True),
    sa.Column('hosting_capacity_max_mw', sa.Float(), nullable=True),
    sa.Column('installed_dg_mw', sa.Float(), nullable=True),
    sa.Column('queued_dg_mw', sa.Float(), nullable=True),
    sa.Column('remaining_capacity_mw', sa.Float(), nullable=True),
    sa.Column('constraining_metric', sa.String(length=100), nullable=True),
    sa.Column('voltage_kv', sa.Float(), nullable=True),
    sa.Column('phase_config', sa.String(length=20), nullable=True),
    sa.Column('is_overhead', sa.Boolean(), nullable=True),
    sa.Column('is_network', sa.Boolean(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_json', sa.JSON(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('raw_attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeders.id'], ),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['hc_ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utility_id', 'feeder_id_external', 'ingestion_run_id', name='uq_hc_record')
    )
    op.create_index('idx_hosting_capacity_records_geom', 'hosting_capacity_records', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_hc_geom', 'hosting_capacity_records', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_hc_ingestion_run', 'hosting_capacity_records', ['ingestion_run_id'], unique=False)
    op.create_index('ix_hc_utility', 'hosting_capacity_records', ['utility_id'], unique=False)
    op.alter_column('balancing_authorities', 'is_rto',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('circuits', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.drop_index(op.f('ix_circuits_feeder_id'), table_name='circuits')
    op.create_index('idx_circuits_geom', 'circuits', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_circuits_geom', 'circuits', ['geom'], unique=False, postgresql_using='gist')
    op.add_column('data_centers', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('data_centers', 'iso_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_data_centers_geom', 'data_centers', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_data_centers_geom', 'data_centers', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_data_centers_iso_id', 'data_centers', ['iso_id'], unique=False)
    op.create_index('ix_data_centers_status', 'data_centers', ['status'], unique=False)
    op.create_index('ix_data_centers_zone_id', 'data_centers', ['zone_id'], unique=False)
    op.add_column('der_locations', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_der_locations_geom', 'der_locations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_der_locations_geom', 'der_locations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_der_locations_source', 'der_locations', ['source'], unique=False)
    op.create_index('ix_der_locations_wattcarbon_asset_id', 'der_locations', ['wattcarbon_asset_id'], unique=False)
    op.alter_column('der_recommendations', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('der_recommendations', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_der_valuations_der_location_id', 'der_valuations', ['der_location_id'], unique=False)
    op.create_index('ix_der_valuations_value_tier', 'der_valuations', ['value_tier'], unique=False)
    op.add_column('feeders', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.drop_index(op.f('ix_feeders_substation_id'), table_name='feeders')
    op.create_index('idx_feeders_geom', 'feeders', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_feeders_geom', 'feeders', ['geom'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_hierarchy_scores_level'), table_name='hierarchy_scores')
    op.create_index('ix_hierarchy_scores_level', 'hierarchy_scores', ['level'], unique=False)
    op.create_index('ix_hierarchy_scores_combined_score', 'hierarchy_scores', ['combined_score'], unique=False)
    op.alter_column('interface_lmps', 'market_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'DA'::character varying"))
    op.alter_column('isos', 'has_decomposition',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('isos', 'has_node_pricing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('isos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('pnode_scores', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pnode_scores', 'pnode_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_pnode_scores_pipeline_run_id', 'pnode_scores', ['pipeline_run_id'], unique=False)
    op.create_index('ix_pnode_scores_pnode_id', 'pnode_scores', ['pnode_id'], unique=False)
    op.add_column('pnodes', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('pnodes', 'iso_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_pnodes_geom', 'pnodes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_pnodes_geom', 'pnodes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_pnodes_iso_id', 'pnodes', ['iso_id'], unique=False)
    op.create_index('ix_pnodes_zone_id', 'pnodes', ['zone_id'], unique=False)
    op.add_column('substations', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_substations_geom', 'substations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_substations_geom', 'substations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_substations_peak_loading_pct', 'substations', ['peak_loading_pct'], unique=False)
    op.add_column('transmission_lines', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_transmission_lines_geom', 'transmission_lines', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_transmission_lines_geom', 'transmission_lines', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_transmission_lines_voltage_kv', 'transmission_lines', ['voltage_kv'], unique=False)
    op.alter_column('zone_classifications', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('zone_classifications', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_zone_classifications_pipeline_run_id', 'zone_classifications', ['pipeline_run_id'], unique=False)
    op.create_index('ix_zone_classifications_zone_id', 'zone_classifications', ['zone_id'], unique=False)
    op.alter_column('zone_lmps', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_zone_lmps_iso_month'), table_name='zone_lmps')
    op.drop_index(op.f('ix_zone_lmps_zone_ts'), table_name='zone_lmps')
    op.create_index('ix_zone_lmps_hour_local', 'zone_lmps', ['hour_local'], unique=False)
    op.create_index('ix_zone_lmps_iso_id', 'zone_lmps', ['iso_id'], unique=False)
    op.create_index('ix_zone_lmps_iso_zone_ts', 'zone_lmps', ['iso_id', 'zone_id', 'timestamp_utc'], unique=False)
    op.create_index('ix_zone_lmps_month', 'zone_lmps', ['month'], unique=False)
    op.create_index('ix_zone_lmps_timestamp_utc', 'zone_lmps', ['timestamp_utc'], unique=False)
    op.create_index('ix_zone_lmps_zone_id', 'zone_lmps', ['zone_id'], unique=False)
    op.add_column('zones', sa.Column('boundary_geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_zones_boundary_geom', 'zones', ['boundary_geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_zones_boundary_geom', 'zones', ['boundary_geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_zones_boundary_geom', table_name='zones', postgresql_using='gist')
    op.drop_index('idx_zones_boundary_geom', table_name='zones', postgresql_using='gist')
    op.drop_column('zones', 'boundary_geom')
    op.drop_index('ix_zone_lmps_zone_id', table_name='zone_lmps')
    op.drop_index('ix_zone_lmps_timestamp_utc', table_name='zone_lmps')
    op.drop_index('ix_zone_lmps_month', table_name='zone_lmps')
    op.drop_index('ix_zone_lmps_iso_zone_ts', table_name='zone_lmps')
    op.drop_index('ix_zone_lmps_iso_id', table_name='zone_lmps')
    op.drop_index('ix_zone_lmps_hour_local', table_name='zone_lmps')
    op.create_index(op.f('ix_zone_lmps_zone_ts'), 'zone_lmps', ['zone_id', 'timestamp_utc'], unique=False)
    op.create_index(op.f('ix_zone_lmps_iso_month'), 'zone_lmps', ['iso_id', 'month'], unique=False)
    op.alter_column('zone_lmps', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_zone_classifications_zone_id', table_name='zone_classifications')
    op.drop_index('ix_zone_classifications_pipeline_run_id', table_name='zone_classifications')
    op.alter_column('zone_classifications', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('zone_classifications', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_transmission_lines_voltage_kv', table_name='transmission_lines')
    op.drop_index('ix_transmission_lines_geom', table_name='transmission_lines', postgresql_using='gist')
    op.drop_index('idx_transmission_lines_geom', table_name='transmission_lines', postgresql_using='gist')
    op.drop_column('transmission_lines', 'geom')
    op.drop_index('ix_substations_peak_loading_pct', table_name='substations')
    op.drop_index('ix_substations_geom', table_name='substations', postgresql_using='gist')
    op.drop_index('idx_substations_geom', table_name='substations', postgresql_using='gist')
    op.drop_column('substations', 'geom')
    op.drop_index('ix_pnodes_zone_id', table_name='pnodes')
    op.drop_index('ix_pnodes_iso_id', table_name='pnodes')
    op.drop_index('ix_pnodes_geom', table_name='pnodes', postgresql_using='gist')
    op.drop_index('idx_pnodes_geom', table_name='pnodes', postgresql_using='gist')
    op.alter_column('pnodes', 'iso_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('pnodes', 'geom')
    op.drop_index('ix_pnode_scores_pnode_id', table_name='pnode_scores')
    op.drop_index('ix_pnode_scores_pipeline_run_id', table_name='pnode_scores')
    op.alter_column('pnode_scores', 'pnode_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pnode_scores', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pipeline_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('pipeline_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('isos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('isos', 'has_node_pricing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('isos', 'has_decomposition',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('interface_lmps', 'market_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'DA'::character varying"))
    op.drop_index('ix_hierarchy_scores_combined_score', table_name='hierarchy_scores')
    op.drop_index('ix_hierarchy_scores_level', table_name='hierarchy_scores')
    op.create_index(op.f('ix_hierarchy_scores_level'), 'hierarchy_scores', ['level', 'entity_id'], unique=False)
    op.drop_index('ix_feeders_geom', table_name='feeders', postgresql_using='gist')
    op.drop_index('idx_feeders_geom', table_name='feeders', postgresql_using='gist')
    op.create_index(op.f('ix_feeders_substation_id'), 'feeders', ['substation_id'], unique=False)
    op.drop_column('feeders', 'geom')
    op.drop_index('ix_der_valuations_value_tier', table_name='der_valuations')
    op.drop_index('ix_der_valuations_der_location_id', table_name='der_valuations')
    op.alter_column('der_recommendations', 'zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('der_recommendations', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_der_locations_wattcarbon_asset_id', table_name='der_locations')
    op.drop_index('ix_der_locations_source', table_name='der_locations')
    op.drop_index('ix_der_locations_geom', table_name='der_locations', postgresql_using='gist')
    op.drop_index('idx_der_locations_geom', table_name='der_locations', postgresql_using='gist')
    op.drop_column('der_locations', 'geom')
    op.drop_index('ix_data_centers_zone_id', table_name='data_centers')
    op.drop_index('ix_data_centers_status', table_name='data_centers')
    op.drop_index('ix_data_centers_iso_id', table_name='data_centers')
    op.drop_index('ix_data_centers_geom', table_name='data_centers', postgresql_using='gist')
    op.drop_index('idx_data_centers_geom', table_name='data_centers', postgresql_using='gist')
    op.alter_column('data_centers', 'iso_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('data_centers', 'geom')
    op.drop_index('ix_circuits_geom', table_name='circuits', postgresql_using='gist')
    op.drop_index('idx_circuits_geom', table_name='circuits', postgresql_using='gist')
    op.create_index(op.f('ix_circuits_feeder_id'), 'circuits', ['feeder_id'], unique=False)
    op.drop_column('circuits', 'geom')
    op.alter_column('balancing_authorities', 'is_rto',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_hc_utility', table_name='hosting_capacity_records')
    op.drop_index('ix_hc_ingestion_run', table_name='hosting_capacity_records')
    op.drop_index('ix_hc_geom', table_name='hosting_capacity_records', postgresql_using='gist')
    op.drop_index('idx_hosting_capacity_records_geom', table_name='hosting_capacity_records', postgresql_using='gist')
    op.drop_table('hosting_capacity_records')
    op.drop_index('ix_rn_year', table_name='resource_needs')
    op.drop_index('ix_rn_utility', table_name='resource_needs')
    op.drop_index('ix_rn_filing', table_name='resource_needs')
    op.drop_table('resource_needs')
    op.drop_index('ix_lf_year', table_name='load_forecasts')
    op.drop_index('ix_lf_utility', table_name='load_forecasts')
    op.drop_index('ix_lf_filing', table_name='load_forecasts')
    op.drop_table('load_forecasts')
    op.drop_index('ix_gc_utility', table_name='grid_constraints')
    op.drop_index('ix_gc_type', table_name='grid_constraints')
    op.drop_index('ix_gc_geom', table_name='grid_constraints', postgresql_using='gist')
    op.drop_index('ix_gc_filing', table_name='grid_constraints')
    op.drop_index('idx_grid_constraints_location_geom', table_name='grid_constraints', postgresql_using='gist')
    op.drop_table('grid_constraints')
    op.drop_index('ix_filing_docs_filing', table_name='filing_documents')
    op.drop_table('filing_documents')
    op.drop_index('ix_iq_utility', table_name='interconnection_queue')
    op.drop_index('ix_iq_type', table_name='interconnection_queue')
    op.drop_index('ix_iq_status', table_name='interconnection_queue')
    op.drop_index('ix_iq_state', table_name='interconnection_queue')
    op.drop_index('ix_iq_geom', table_name='interconnection_queue', postgresql_using='gist')
    op.drop_index('idx_interconnection_queue_geom', table_name='interconnection_queue', postgresql_using='gist')
    op.drop_table('interconnection_queue')
    op.drop_table('hosting_capacity_summaries')
    op.drop_table('hc_ingestion_runs')
    op.drop_index('ix_filings_utility', table_name='filings')
    op.drop_index('ix_filings_type', table_name='filings')
    op.drop_index('ix_filings_regulator', table_name='filings')
    op.drop_index('ix_filings_docket', table_name='filings')
    op.drop_table('filings')
    op.drop_index('ix_utilities_state', table_name='utilities')
    op.drop_index('ix_utilities_regulator_id', table_name='utilities')
    op.drop_index('ix_utilities_iso_id', table_name='utilities')
    op.drop_index('ix_utilities_eia_id', table_name='utilities')
    op.drop_table('utilities')
    op.drop_table('regulators')
    # ### end Alembic commands ###
